PRAGMA foreign_keys = ON;

INSERT INTO teams(abbr, name) VALUES ("ARI", "Arizona Diamondbacks");
INSERT INTO teams(abbr, name) VALUES ("ATL", "Atlanta Braves");
INSERT INTO teams(abbr, name) VALUES ("BAL", "Baltimore Orioles");
INSERT INTO teams(abbr, name) VALUES ("BOS", "Boston Red Sox");
INSERT INTO teams(abbr, name) VALUES ("CHC", "Chicago Cubs");
INSERT INTO teams(abbr, name) VALUES ("CHW", "Chicago White Sox");
INSERT INTO teams(abbr, name) VALUES ("CIN", "Cincinnati Reds");
INSERT INTO teams(abbr, name) VALUES ("CLE", "Cleveland Guardians");
INSERT INTO teams(abbr, name) VALUES ("COL", "Colorado Rockies");
INSERT INTO teams(abbr, name) VALUES ("DET", "Detroit Tigers");
INSERT INTO teams(abbr, name) VALUES ("MIA", "Miami Marlins");
INSERT INTO teams(abbr, name) VALUES ("HOU", "Houston Astros");
INSERT INTO teams(abbr, name) VALUES ("KC", "Kansas City Royals");
INSERT INTO teams(abbr, name) VALUES ("LAA", "Los Angeles Angels");
INSERT INTO teams(abbr, name) VALUES ("LAD", "Los Angeles Dodgers");
INSERT INTO teams(abbr, name) VALUES ("MIL", "Milwaukee Brewers");
INSERT INTO teams(abbr, name) VALUES ("MIN", "Minnesota Twins");
INSERT INTO teams(abbr, name) VALUES ("NYM", "New York Mets");
INSERT INTO teams(abbr, name) VALUES ("NYY", "New York Yankees");
INSERT INTO teams(abbr, name) VALUES ("OAK", "Oakland Athletics");
INSERT INTO teams(abbr, name) VALUES ("PHI", "Philadelphia Phillies");
INSERT INTO teams(abbr, name) VALUES ("PIT", "Pittsburgh Pirates");
INSERT INTO teams(abbr, name) VALUES ("SD", "San Diego Padres");
INSERT INTO teams(abbr, name) VALUES ("SF", "San Francisco Giants");
INSERT INTO teams(abbr, name) VALUES ("SEA", "Seattle Mariners");
INSERT INTO teams(abbr, name) VALUES ("STL", "St. Louis Cardinals");
INSERT INTO teams(abbr, name) VALUES ("TB", "Tampa Bay Rays");
INSERT INTO teams(abbr, name) VALUES ("TX", "Texas Rangers");
INSERT INTO teams(abbr, name) VALUES ("TOR", "Toronto Blue Jays");
INSERT INTO teams(abbr, name) VALUES ("WAS", "Washington Nationals");